name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
    lint-and-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "20" # Astro recommends Node 18+
              
            - name: Install dependencies
              run: npm install
              
            - name: Run ESLint
              run: npx eslint . --ext .js --ext .astro --ext .mdx
            
            - name: Run Prettier check
              run: npx prettier --check .

            - name: Build Astro site
              run: npm run build